fix(arc-444): drop table support for rich  text editor
since it causes major build issues in the client:
* editorState.setConvertOptions is not a function
* TypeError: Cannot read properties of undefined (reading 'prototype')